name = "Spectra"
uuid = "9da5bd80-4f3d-48a2-a37e-447dff2ef7bc"
authors = ["Carlos A. Michelén Ströfer <c.michelen.strofer@gmail.com>"]
version = "0.1.0"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
